AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "examples/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Layout/LineLength:
  Max: 120

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Metrics/MethodLength:
  Max: 35
  Exclude:
    - "test/**/*"

Metrics/AbcSize:
  Max: 40
  Exclude:
    - "test/**/*"

Metrics/CyclomaticComplexity:
  Max: 10

Naming/VariableNumber:
  Enabled: false

Metrics/ClassLength:
  Max: 250

Metrics/BlockLength:
  Max: 30
  Exclude:
    - "test/**/*"

Naming/MethodParameterName:
  Enabled: false
